version: '3'
services:
  db:
    image: postgres:latest
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    environment:
      - DATABASE_DOMAIN=${DATABASE_DOMAIN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_DOMAIN}/${POSTGRES_DB}
      - WEB_DOMAIN=${WEB_DOMAIN}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:8000"
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


  # web:
  #   entrypoint: /bin/echo "`web` disabled; use Flask dev server instead (flask run --reload)"
  #   restart: no
