#!/bin/bash

# Set the compose files
COMPOSE_DIR="docker_compose"
COMPOSE_FILES="-f $COMPOSE_DIR/docker-compose.yml -f $COMPOSE_DIR/docker-compose.embed.yml"
ENV_FILE=".env"
IS_DEVELOP=false

# 'docker' GID must match the host's GID for the socket
export DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)

if [ "$FLASK_ENV" == "development" ]; then
    echo "RUNNING IN DEVELOPMENT MODE..."
    IS_DEVELOP=true
    COMPOSE_FILES="-f $COMPOSE_DIR/docker-compose.yml -f $COMPOSE_DIR/docker-compose.override.yml"
fi

# Function to start the Docker containers
start_containers() {
    echo "Starting Docker containers..."
    docker compose --env-file $ENV_FILE $COMPOSE_FILES up --build -d
    echo "Containers started."
}

# Function to stop the Docker containers
stop_containers() {
    echo "Stopping Docker containers..."
    docker compose --env-file $ENV_FILE $COMPOSE_FILES down
    echo "Containers stopped."
}

# Function to destroy the Docker containers
destroy_containers() {
    echo "Destroying Docker containers..."
    docker compose --env-file $ENV_FILE $COMPOSE_FILES down --volumes
    echo "Containers destroyed."
}

# Function to purge the Docker containers and images
purge_containers() {
    echo "Purging Docker containers and images..."
    docker compose --env-file $ENV_FILE $COMPOSE_FILES down --rmi all --volumes
    echo "Containers and images purged."
}

# Function to show the status of the Docker containers
status_containers() {
    docker compose --env-file $ENV_FILE $COMPOSE_FILES ps
}

# Function to show docker logs
logs_containers() {
    docker compose --env-file $ENV_FILE $COMPOSE_FILES logs -f
}

# Function to show usage
usage() {
    echo f"
Usage: $0 <command>

Note: Set the FLASK_ENV environment variable to 'development' to use the docker-compose.override.yml file.

Commands:
    start | up      (Re)start (and build) the Docker containers
    stop | down     Stop the Docker containers
    status | ps     Show the status of the Docker containers
    destroy | rm    Destroy the Docker containers
    purge | bye     Purge the Docker containers and images
    logs | log      Show docker logs
    help            Show this help message
    "

    exit 1
}

# Main script
case "$1" in
    start | up)
        start_containers
        ;;
    stop | down)
        stop_containers
        ;;
    status | ps)
        status_containers
        ;;
    destroy | rm)
        destroy_containers
        ;;
    purge | bye)
        purge_containers
        ;;
    logs | log)
        logs_containers
        ;;
    *)
        usage
        ;;
esac
